# scrolling config
touch_scroll_multiplier 9.0
wheel_scroll_multiplier 2.0


# font config
font_family       JetBrainsMono Nerd Font
font_size         12


# opacity
background_opacity 0.80


# open kitty in same directory
map ctrl+super+enter      new_os_window_with_cwd


# miscellaneous
allow_remote_control yes

# kitty borders
# cursor_trail 1 


# border
window_padding_width 0 5 

remember_window_size  no
resize_in_steps       yes
