󰖳 + x : dpms on
󰖳 + b : toggle waybar
󰖳 + a : toggle fullscreen
󰖳 + f : toggle floating view
󰖳 + w : wallpaper switcher
ctrl + space : application launcher
󰖳 + v : clipboard (text)
󰖳 + ctrl + v : clilpboard (img)
󰖳 + enter : kitty
ctrl + 󰖳 + enter : kitty (pwd)
󰖳 + e : dolphin
󰖳 + z : browser
ctrl + 󰖳 + q : kill selected window
shift + scroll up : brightness +
shift + scroll down : brightness -
󰖳 + scroll up : vol +
󰖳 + scroll down : vol -
󰖳 + r : resize window (vim)
ctrl + 󰖳 + m : laptop monitor toggle
ctrl + 󰖳 + s : keybinds helper
󰖳 + Space : toggle dwindle/scrolling
