#!/bin/bash

# Aggressive CPU power saving
echo 8  > /sys/devices/system/cpu/intel_pstate/min_perf_pct
echo 15  > /sys/devices/system/cpu/intel_pstate/max_perf_pct
echo 1  > /sys/devices/system/cpu/intel_pstate/no_turbo

# Lowest platform power profile
echo quiet | sudo tee /sys/firmware/acpi/platform_profile > /dev/null
