# this tool options
󰓎  MASTER FOLDER :               kitty -d ~/scripts/scripts-plugin/
󰓎  EDIT ENTRIES :                kitty --hold nvim ~/scripts/scripts-plugin/entries.conf


# wallpaper switcher
Wallpaper Switcher :          ~/scripts/wallpaper_switcher/wallpaper_switcher.sh


# hyprland config files
Kitty Config :                kitty --hold nvim ~/.config/kitty/kitty.conf
Keybindings :                 kitty --hold nvim ~/.config/hypr/modules/keybinds.conf
Autostart :                   kitty --hold nvim ~/.config/hypr/modules/autostart.conf
Decorations :                 kitty --hold nvim ~/.config/hypr/modules/decoratons.conf
Default Config :              kitty --hold nvim ~/.config/hypr/modules/hyprland.conf
Scrolling Config :            kitty --hold nvim ~/.config/hypr/modules/scrolling.conf

# custom other rofi menus
Snippets :                    ~/scripts/snippets/snippets.sh

# cartoons
Shinchan :                    ~/scripts/player/shinchan/player.sh
Doraemon :                    ~/scripts/player/doraemon/doraemon.sh
Ninja Hattori:                ~/scripts/player/ninja/player.sh

# webapps suite
Webapps :                     kitty bash -c "source /home/rudra/scripts/webapps/master.sh; exec bash"

# open custom notes
Watchlist :                   kitty --hold nvim ~/scripts/watchlist/list.conf

# tutorial
Apna College C Tutorial :     mpv ~/code/sources/c-tutorial-apna-college.webm
Apna College C Tutorial (vlc) :     vlc ~/code/sources/c-tutorial-apna-college.webm
