background {
    monitor =
    path = ~/Pictures/bin/current
    # Smooth aesthetic blur (like the example image)
    blur_passes = 2                      # 0 to disable blurring
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.7000
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# ------------------------------------------
# PASSWORD INPUT BOX
# ------------------------------------------
input-field {
    monitor =
    size = 350, 70 
    outline_thickness = 3
    dots_size = 0.25 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    
    # Modern monochrome styling
    outer_color = rgba(200, 200, 200, 0.8)
    inner_color = rgba(30, 30, 30, 0.7)
    font_color = rgb(242, 242, 242)
    
    fade_on_empty = false
    placeholder_text = <i>Password...</i> # Text rendered in the input box
    hide_input = false
    
    position = 0, -120
    halign = center
    valign = center
}

# ------------------------------------------
# LARGE DIGITAL CLOCK
# ------------------------------------------
label {
    monitor =
    text = $TIME12
    color = rgba(242, 242, 242, 0.9)
    font_size = 140 
    font_family = JetBrains Mono Nerd Font ExtraBold # Fallbacks nicely to generic sans if missing
    
    position = 0, 150
    halign = center
    valign = center
}

# ------------------------------------------
# AESTHETIC DATE LABEL
# ------------------------------------------
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%a, %b %d')" # Displays as: Thu, May 21
    color = rgba(242, 242, 242, 0.6)                    # Slightly dimmer for hierarchy
    font_size = 25 
    font_family = JetBrains Mono Nerd Font
    position = 0, 30                                    # Tucked right under the main clock
    halign = center 
    valign = bottom
}
# ------------------------------------------
# WELCOME USERNAME TAG
# ------------------------------------------
label {
    monitor =
    text = Welcome back, rudra 
    color = rgba(242, 242, 242, 0.7)
    font_size = 40
    font_family = JetBrains Mono Nerd Font
    
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = Arch + Hyprland
    color = rgba(242, 242, 242, 0.6)                    # Slightly dimmer for hierarchy
    font_size = 12 
    font_family = JetBrains Mono Nerd Font
    position = 0, -20                                    # Tucked right under the main clock
    halign = center 
    valign = top
}

