general {
    lock_cmd = pidof hyprlock || hyprlock

    # 2. BEFORE SLEEP: Use the new Lua syntax to disable the display
    #before_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && sleep 0.5 && loginctl lock-session
    before_sleep_cmd = loginctl lock-session

    # 3. AFTER WAKE: Use the new Lua syntax to enable the display
    after_sleep_cmd = sleep 2 && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
