#!/bin/bash
#cliphist list | grep "\[\[ binary data"| rofi -dmenu -theme-str 'listview { columns : 1; }' -theme-str 'element-icon { enabled : false; }' -display-columns 2 -p "Copy Image  " -theme ~/.config/rofi/config.rasi | cliphist decode | wl-copy 



#cliphist list | grep "\[\[ binary data"| rofi -dmenu -show-icons

#./helper | rofi -dmenu -show-icons -theme-str 'element-icon { size: 15em; }' -theme-str 'element-text {enabled : false;}' -theme-str 'listview {lines : 2;}' -theme-str 'element {children:[dummy,element-icon,dummy];}' -theme-str 'dummy {background-color:transparent;}' -theme-str 'element {padding:0px;}'




#/home/rudra/scripts/clipboard/helper | rofi -dmenu -p "Copy Image  " -show-icons -theme-str 'element-icon { size: 15em; }' -theme-str 'element-text {enabled : false;}' -theme-str 'listview {lines : 2;}' -theme-str 'element {children:[dummy,element-icon,dummy];}' -theme-str 'dummy {background-color:transparent;}' -theme-str 'element {padding:0px;}' | cliphist decode | wl-copy


bash /home/rudra/scripts/clipboard/helper | rofi -dmenu -p "Copy Image  " -show-icons -theme-str 'element-icon { size: 15em; }' -theme-str 'element-text {enabled : false;}' -theme-str 'listview {lines : 2;}' -theme-str 'element {children:[dummy,element-icon,dummy];}' -theme-str 'dummy {background-color:transparent;}' -theme-str 'element {padding:0px;}' | cliphist decode | wl-copy
