#!/bin/bash
cliphist list | grep -a -v "[[ binary data * ]]" | rofi -i -dmenu -theme-str 'listview { columns : 1; }' -theme-str 'element-icon { enabled : false; }' -display-columns 2 -p "Copy Text  " -theme ~/.config/rofi/config.rasi | cliphist decode | wl-copy

