# display on after dpms off
bind = SUPER, X, exec, hyprctl dispatch dpms on


# toggle waybar without killing it
bind = SUPER, B, exec, killall -SIGUSR1 waybar


# toggle fullscreen
bind = $win, A, fullscreen


# wallpaper switcher# wallpaper switcher# wallpaper switcher
bind = $win, W, exec, ~/scripts/wallpaper_switcher/wallpaper_switcher.sh
